[package]
name = "fibonacci"
version = "1.1.0"
edition = "2024"
publish = false

[dependencies]
alloy-sol-types = { workspace = true }
fibonacci-lib = { path = "../lib" }
zkm-zkvm = { git = "https://github.com/zkMIPS/zkMIPS.git" }
